{% set name = "pyinterpolate" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyinterpolate-{{ version }}.tar.gz
  sha256: 1b826d4333a9a5cd34dc900b793c8982d49a211402a5d906851b88c70e57eeac

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - tqdm
    - descartes
    - prettytable
    - rtree
    - pyogrio
    - geopandas
    - pandas
    - scipy
    - dask-core
    - numpy
    - matplotlib-base
    - shapely
    - pyarrow
    - pylibtiff >=0.6.1
    - deprecation

test:
  imports:
    - pyinterpolate

about:
  home: https://github.com/DataverseLabs/pyinterpolate
  summary: Spatial Interpolation in Python
  dev_url: https://github.com/DataverseLabs/pyinterpolate
  license: BSD-3-Clause
  license_file: license.txt

extra:
  recipe-maintainers:
    - SimonMolinsky
