{% set name = "pyinterpolate" %}
{% set version = "0.3.4.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyinterpolate-{{ version }}.tar.gz
  sha256: 887cde6dd0e8fbea2bdbddcd9f45a0e8516e44b63f121a62d63be217bf0dcb21

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - tqdm
    - descartes
    - prettytable
    - rtree
    - requests
    - pyogrio
    - geopandas
    - pandas
    - scipy
    - dask-core
    - numpy
    - matplotlib-base

test:
  imports:
    - pyinterpolate

about:
  home: https://github.com/DataverseLabs/pyinterpolate
  summary: Spatial Interpolation in Python
  dev_url: https://github.com/DataverseLabs/pyinterpolate
  license: BSD-3-Clause
  license_file: license.txt

extra:
  recipe-maintainers:
    - SimonMolinsky
